Repository iqm-finland/iqm-benchmarks, pull requests merged in 2024-12, with the labels that each got.

#9 New base class for mGST and improvements to mGST+GHZ
  .gitignore
  CHANGELOG.rst
  README.md
  examples/example_experiment_all.ipynb
  examples/example_ghz.ipynb
  examples/example_gst.ipynb
  examples/how_to_make_your_own_benchmark.ipynb
  src/iqm/benchmarks/compressive_gst/compressive_gst.py
  src/iqm/benchmarks/compressive_gst/gst_analysis.py
  src/iqm/benchmarks/entanglement/ghz.py
  src/iqm/benchmarks/utils.py
  tests/test_ghz.py
  tests/test_gst.py
Labels: documentation, enhancement

#14 Fix observation outputs in QV & small bug in CLOPS
  CHANGELOG.rst
  src/iqm/benchmarks/quantum_volume/clops.py
  src/iqm/benchmarks/quantum_volume/quantum_volume.py
Labels: bug

#16 Fix miscellaneous bugs
  CHANGELOG.rst
  examples/example_experiment_all.ipynb
  examples/example_qscore.ipynb
  src/iqm/benchmarks/benchmark_experiment.py
  src/iqm/benchmarks/optimization/qscore.py
  src/iqm/benchmarks/randomized_benchmarking/randomized_benchmarking_common.py
Labels: bug

#15 Add classes for better handling of quantum circuits
  CHANGELOG.rst
  src/iqm/benchmarks/__init__.py
  src/iqm/benchmarks/benchmark_definition.py
  src/iqm/benchmarks/circuit_containers.py
  src/iqm/benchmarks/compressive_gst/compressive_gst.py
  src/iqm/benchmarks/entanglement/ghz.py
  src/iqm/benchmarks/optimization/qscore.py
  src/iqm/benchmarks/quantum_volume/clops.py
  src/iqm/benchmarks/quantum_volume/quantum_volume.py
  src/iqm/benchmarks/randomized_benchmarking/clifford_rb/clifford_rb.py
  src/iqm/benchmarks/randomized_benchmarking/interleaved_rb/interleaved_rb.py
  src/iqm/benchmarks/randomized_benchmarking/mirror_rb/mirror_rb.py
  src/iqm/benchmarks/randomized_benchmarking/randomized_benchmarking_common.py
  src/iqm/benchmarks/readout_mitigation.py
  src/iqm/benchmarks/utils.py
  src/mGST/qiskit_interface.py
  tests/test_ghz.py
  tests/test_gst.py
  tests/unit/test_benchmark_circuit.py
Labels: enhancement

#18 Fix RB plot bug
  CHANGELOG.rst
  src/iqm/benchmarks/randomized_benchmarking/randomized_benchmarking_common.py
Labels: bug

#22 QScore rebasing
  examples/example_experiment_all.ipynb
  examples/example_qscore.ipynb
  src/iqm/benchmarks/benchmark_experiment.py
  src/iqm/benchmarks/optimization/qscore.py
  tests/test_qscore.py
Labels: enhancement
